apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-reminders
  labels:
    app.kubernetes.io/name: go-reminders
    app.kubernetes.io/instance: go-reminders
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-reminders
      app.kubernetes.io/instance: go-reminders
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-reminders
        app.kubernetes.io/instance: go-reminders
    spec:
      containers:
        - name: go-reminders
          image: "tdhite/go-reminders:latest"
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: go-reminders-secretsmap
          - configMapRef:
              name: go-reminders-configmap 
          ports:
          - name: go-reminders
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /stats/hits
              port: go-reminders
          readinessProbe:
            httpGet:
              path: /stats/hits
              port: go-reminders
          resources:
            {}
      imagePullSecrets:
        - name: go-reminders-registry-creds
