apiVersion: v1
kind: Service
metadata:
  name: go-reminders
  labels:
    app.kubernetes.io/name: go-reminders
    app.kubernetes.io/instance: go-reminders
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: go-reminders
      protocol: TCP
      name: go-reminders
  selector:
    app.kubernetes.io/name: go-reminders
    app.kubernetes.io/instance: go-reminders
